version: 2.1

orbs:
  python: rohanpm/python@1.1.1

workflows:
  version: 2
  ci-cd:
    jobs:
    - python/tox:
        name: Autotests
        toxenv: py36
        executor: python/python36
        persist_coverage: true
        filters: &ci_filters
          branches:
            ignore: gh-pages
          tags:
            only: /^v.*/
    - python/tox:
        name: Static checks
        toxenv: static
        filters:
          <<: *ci_filters
    - python/tox:
        name: API compatibility check
        toxenv: pidiff
        filters:
          <<: *ci_filters
    - python/coveralls:
        name: Submit coverage results to coveralls
        requires:
        - Autotests
        context: pidiff-secrets
        filters:
          <<: *ci_filters
    - python/tox:
        name: Build docs
        toxenv: docs
        # For pushing to gh-pages
        context: pidiff-secrets
        post-steps:
        - run: scripts/push-docs
        filters:
          <<: *ci_filters
    - python/codeclimate-upload-coverage:
        name: Submit coverage results to codeclimate
        test_reporter_id: b5167e87a147f386af54fb218c710b65bafa6391ceeb2f37f82525f16eb32fc2
        requires:
        - Autotests
        filters:
          <<: *ci_filters
    - python/release:
        name: Release to PyPI
        # For twine credentials
        context: pidiff-secrets
        # Only release if all tests passed
        requires:
        - Autotests
        - Static checks
        filters:
          <<: *ci_filters
