version: 2.1

orbs:
  python: rohanpm/python@1.3.0

workflows:
  version: 2
  ci-cd:
    jobs:
    - python/tox:
        name: Python 3.8 tests
        toxenv: py38
        executor: python/python38
        filters: &ci_filters
          branches:
            ignore: gh-pages
          tags:
            only: /^v.*/
    - python/tox:
        name: Static checks
        toxenv: static
        filters:
          <<: *ci_filters
    - python/tox:
        name: API compatibility check
        toxenv: pidiff
        filters:
          <<: *ci_filters
    - python/tox:
        name: Build docs
        toxenv: docs
        # For pushing to gh-pages
        context: pidiff-secrets
        post-steps:
        - run: scripts/push-docs
        filters:
          <<: *post_merge_filters
    - python/release:
        name: Release to PyPI
        # For twine credentials
        context: pidiff-secrets
        # Only release if all tests passed
        requires:
        - Python 3.8 tests
        - Static checks
        filters:
          <<: *post_merge_filters
